services:
  server:
    image: owenrbee/hands-free-api:latest
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - BACKEND=${BACKEND}
      - VAD_THRESHOLD=${VAD_THRESHOLD}
      - SILENCE_DURATION_MS=${SILENCE_DURATION_MS}
      - MAX_OUTPUT_TOKENS=${MAX_OUTPUT_TOKENS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - ALLOWED_GMAIL_ACCOUNTS=${ALLOWED_GMAIL_ACCOUNTS}
      - SESSION_KEY=${SESSION_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: always

  frontend:
    image: owenrbee/hands-free-ux:latest
    environment:
      - BACKEND_URL=http://server:8080
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - server
